export const actionTypes = {
  SET_CURRENCY_SYMBOL: "SET_CURRENCY_SYMBOL",
  SET_ATTRS_FROM_CATEGORY: "SET_ATTRS_FROM_CATEGORY",
  SET_SELECTED_ATTRS: "SET_SELECTED_ATTRS",
  SET_CATEGORY_PRODUCTS: "SET_CATEGORY_PRODUCTS",
  SET_MAIN_CATEGORY: "SET_MAIN_CATEGORY",
  ADD_TO_CART: "ADD_TO_CART",
  TOGGLE_CART_OVERLAY: "TOGGLE_CART_OVERLAY",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_MODAL_PRODUCT: "SET_MODAL_PRODUCT",
  INCREMENT_ITEM: "INCREMENT_ITEM",
  DECREMENT_ITEM: "DECREMENT_ITEM",
};
